In [7]:
import main
import numpy as np

In [3]:
a = main.GA()

TypeError: __init__() missing 2 required positional arguments: 'pop_size' and 'gene_options'

In [4]:
ex =[[1,2],[3,4,5]]

sizes = [len(a) for a in ex]

In [7]:
import numpy as np

In [17]:
size = 50 

input = np.array(ex[0])

np.random.randint(0,len(input),size)

randon_feature = lambda size, array: np.array(array)[np.random.randint(0,len(array),size)]



In [21]:
np.array(list(map(randon_feature,[size]*len(ex), ex))).transpose()

array([[1, 4],
       [1, 3],
       [2, 5],
       [1, 3],
       [1, 3],
       [1, 3],
       [1, 5],
       [1, 4],
       [1, 5],
       [1, 5],
       [1, 3],
       [1, 3],
       [2, 5],
       [2, 3],
       [2, 3],
       [2, 3],
       [1, 3],
       [1, 3],
       [1, 5],
       [1, 3],
       [2, 4],
       [1, 3],
       [1, 4],
       [2, 4],
       [2, 4],
       [1, 4],
       [1, 4],
       [1, 3],
       [2, 3],
       [1, 5],
       [2, 5],
       [2, 5],
       [1, 3],
       [1, 4],
       [1, 5],
       [2, 4],
       [2, 4],
       [2, 3],
       [1, 5],
       [2, 4],
       [2, 3],
       [2, 4],
       [2, 5],
       [1, 5],
       [2, 4],
       [1, 3],
       [1, 3],
       [1, 5],
       [1, 5],
       [2, 4]])

In [23]:
def generate_genes(sample,size):
    
    randon_feature = lambda size, array: np.array(array)[np.random.randint(0,len(array),size)]
    
    return np.array(list(map(randon_feature,[size]*len(sample), sample))).transpose()

generate_genes(ex,10)

array([[1, 4],
       [1, 5],
       [1, 4],
       [1, 4],
       [2, 3],
       [1, 4],
       [1, 4],
       [2, 5],
       [2, 4],
       [2, 3]])

In [13]:
a.genes

array([[1, 4],
       [1, 3],
       [2, 4],
       [2, 3],
       [2, 3],
       [1, 4],
       [2, 3],
       [1, 4],
       [1, 3],
       [2, 5],
       [1, 5],
       [1, 4],
       [1, 5],
       [2, 3],
       [1, 3],
       [1, 3],
       [2, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 4],
       [2, 5],
       [2, 4],
       [1, 3],
       [1, 4],
       [1, 5],
       [2, 3],
       [1, 5],
       [2, 5],
       [1, 5],
       [2, 3],
       [2, 4],
       [1, 3],
       [2, 3],
       [2, 3],
       [2, 5],
       [2, 3],
       [1, 4],
       [2, 5],
       [1, 5],
       [2, 5],
       [1, 4],
       [1, 4],
       [2, 5],
       [2, 4],
       [1, 5],
       [2, 5],
       [1, 4],
       [1, 5]])

In [12]:
a = main.GA(50,ex,np.sum)#.genes

a.get_fitness()

a.fitness_scores

array([5, 4, 6, 5, 5, 5, 5, 5, 4, 7, 6, 5, 6, 5, 4, 4, 5, 5, 5, 6, 7, 6,
       7, 6, 4, 5, 6, 5, 6, 7, 6, 5, 6, 4, 5, 5, 7, 5, 5, 7, 6, 7, 5, 5,
       7, 6, 6, 7, 5, 6])

In [28]:
import numpy as np

a = np.array([[1,2],[3,4]])

a[[1,0],[0,1]]

array([3, 2])

In [32]:
np.array(list(map(np.sum,a)))

array([3, 7])

In [14]:
1 if 1>2 else 0

0

In [27]:
lambda size: np.array(
    (np.arange(start= 0, stop = 10),
     np.random.randint(low = 0, high = 2, size = 10))).transpose().reshape(-1,2)

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 1],
       [4, 1],
       [5, 0],
       [6, 1],
       [7, 0],
       [8, 1],
       [9, 0]])